/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DoiMatKhauDao;
import DATA.DataValidator;
import DATA.MessageDialogHelper;
import DATA.ShareData;
import DTO.NguoiDung;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class DoiMaKhau extends javax.swing.JPanel {
    private DoiMaKhau dk;

    /**
     * Creates new form DoiMaKhau
     */
    public DoiMaKhau() {
        initComponents();
        XuLyMK();
        
    }

    private void XuLyMK() {
        txtTenNguoiDung.setText(ShareData.takhoanDangNhap.getTenND());
        txtUserName.setText(ShareData.takhoanDangNhap.getUserName());
        txtTenNguoiDung.setEnabled(false);
        txtUserName.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtTenNguoiDung = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        jpassUser = new javax.swing.JPasswordField();
        txtConfirmPass = new javax.swing.JPasswordField();
        jcboxHienThi = new javax.swing.JCheckBox();
        btnHuy = new javax.swing.JButton();
        btnDoiMK = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Đổi Mật Khẩu");

        jcboxHienThi.setText(" Hiện Mật Khẩu");
        jcboxHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxHienThiActionPerformed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Cancel-24.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnDoiMK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Edit-24.png"))); // NOI18N
        btnDoiMK.setText("Đổi Mật Khẩu");
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("ConfirmPassNew:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("UserPassNew:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("UserName:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tên Người Dùng:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTenNguoiDung, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jpassUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jcboxHienThi))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDoiMK)
                                .addGap(49, 49, 49)
                                .addComponent(btnHuy)))))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenNguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpassUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcboxHienThi)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnDoiMK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcboxHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxHienThiActionPerformed
        // TODO add your handling code here:
        if (jcboxHienThi.isSelected()) {
            jpassUser.setEchoChar((char) 0);
            txtConfirmPass.setEchoChar((char) 0);
        } else {
            jpassUser.setEchoChar('*');
            txtConfirmPass.setEchoChar('*');
        }
    }//GEN-LAST:event_jcboxHienThiActionPerformed

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validdateEmpty(jpassUser, sb, "Mật khẩu mới không được để trống");
        DataValidator.validdateEmpty(txtConfirmPass, sb, "Mật khẩu lặp không được để trống");

        if( sb.length()>0)
        {
            MessageDialogHelper.showErrorDialog(this,sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(dk,"Bạn có muốn đổi pass không","Hỏi?")== JOptionPane.NO_OPTION)
        {
            return;
        }

        try{

            NguoiDung nd = new NguoiDung();
            nd.setMaND(ShareData.takhoanDangNhap.getMaND());
            nd.setUserPass(jpassUser.getText());
            if(jpassUser.getText().length()<6){
                MessageDialogHelper.showMessageDialog(dk, "Mật khẩu  phải ít nhất 6 kí tự!", "Thông báo !");
                return;
            }else{
                if(jpassUser.getText().trim().equals(ShareData.takhoanDangNhap.getUserPass().trim())){
                    MessageDialogHelper.showMessageDialog(dk, "Mật khẩu  trùng với mật khẩu hiện tại!", "Thông báo !");
                    return;
                }else{
                    if(jpassUser.getText().equals(txtConfirmPass.getText())){

                        DoiMatKhauDao dao = new DoiMatKhauDao();
                        if(dao.update(nd))
                        {
                            MessageDialogHelper.showMessageDialog(dk, "Mật khẩu  đã đươc đổi!", "Thông báo !");
                            XoaTrang();

                        }
                        else
                        {
                            MessageDialogHelper.showConfirmDialog(dk, "Mật khẩu không được đổi do lỗi !","Cảnh báo!");
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Mật khẩu lặp lại sai mời kiểm tra lại!");
                    }
                }
                
            }
            

        }
        catch( Exception e)
        {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(dk,e.getMessage(),"Lỗi!");
        }
    }//GEN-LAST:event_btnDoiMKActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        int index= MainForm.tblMainBoard.indexOfComponent(this);
        MainForm.tblMainBoard.removeTabAt(index);
       
    }//GEN-LAST:event_btnHuyActionPerformed

    private void XoaTrang(){
        jpassUser.setText("");
        txtConfirmPass.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox jcboxHienThi;
    private javax.swing.JPasswordField jpassUser;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JTextField txtTenNguoiDung;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
