/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DATA.ShareData;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {
    private QuanLyKhachHang mQuanLyKhachHang;
    private QuanLyThongTinXe mQuanLyThongTinXe;
    private QuanLyPhieuThue mQuanLyPhieuThue;
    private QuanLyXeMay mQuanLyXeMay;
    private QuanLyXeTai mQuanLyXeTai;
    private QuanLyOTo mQuanLyOTo;
    private QuanLyPhieuPhat mPhieuPhat;
    private QuanLyNhanVien mQuanLyNhanVien;
    private DoiMaKhau mDoiMaKhau;
    private ThongKeView mThongKeView;
//    private TimKiemKhachHang mTimKiemKhachHang;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblMainBoard = new javax.swing.JTabbedPane();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDoiMatKhau = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        btnQLKH = new javax.swing.JButton();
        jsp10 = new javax.swing.JToolBar.Separator();
        btnQLNV = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        btnQLXM = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        btnQLOT = new javax.swing.JButton();
        jSeparator20 = new javax.swing.JToolBar.Separator();
        btnQLXT = new javax.swing.JButton();
        jSeparator21 = new javax.swing.JToolBar.Separator();
        btnTTX = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        btnHD = new javax.swing.JButton();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        btnPP = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnThongKe = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuManageKhachHang = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuManageNhanVien = new javax.swing.JMenuItem();
        jsp2 = new javax.swing.JPopupMenu.Separator();
        menuManageLoaiXe = new javax.swing.JMenu();
        menuManageXeMay = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        menuManageXeTai = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        menuManageOto = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuManageThongTinXe = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuManagerHopDong = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuManagerPhieuPhat = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        menuXuatBaoCao = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuDangXuat = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuDoiMatKhau = new javax.swing.JMenuItem();
        jsp9 = new javax.swing.JPopupMenu.Separator();
        menuThoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblMainBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tblMainBoardMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/bg.png"))); // NOI18N
        tblMainBoard.addTab("", jLabel4);

        jToolBar1.setRollover(true);

        btnDoiMatKhau.setBackground(new java.awt.Color(255, 204, 204));
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Manager-24.png"))); // NOI18N
        btnDoiMatKhau.setText("Đổi Mật Khẩu");
        btnDoiMatKhau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoiMatKhau.setFocusable(false);
        btnDoiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoiMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDoiMatKhau);
        jToolBar1.add(jSeparator11);

        btnQLKH.setBackground(new java.awt.Color(255, 204, 204));
        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Customer-24.png"))); // NOI18N
        btnQLKH.setText("Quản lý khách hàng");
        btnQLKH.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQLKH.setFocusable(false);
        btnQLKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLKH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLKH);
        jToolBar1.add(jsp10);

        btnQLNV.setBackground(new java.awt.Color(255, 204, 204));
        btnQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Staff-24.png"))); // NOI18N
        btnQLNV.setText("Quản lý nhân viên");
        btnQLNV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQLNV.setFocusable(false);
        btnQLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNVActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLNV);
        jToolBar1.add(jSeparator12);

        btnQLXM.setBackground(new java.awt.Color(255, 204, 204));
        btnQLXM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/motorcyclist-icon.png"))); // NOI18N
        btnQLXM.setText("Quản lý xe máy");
        btnQLXM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQLXM.setFocusable(false);
        btnQLXM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLXM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLXM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLXMActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLXM);
        jToolBar1.add(jSeparator13);

        btnQLOT.setBackground(new java.awt.Color(255, 204, 204));
        btnQLOT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Travel-BMV-icon24.png"))); // NOI18N
        btnQLOT.setText("Quản lý ô tô");
        btnQLOT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQLOT.setFocusable(false);
        btnQLOT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLOT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLOTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLOT);
        jToolBar1.add(jSeparator20);

        btnQLXT.setBackground(new java.awt.Color(255, 204, 204));
        btnQLXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Lorry-icon24.png"))); // NOI18N
        btnQLXT.setText("Quản lý xe tải");
        btnQLXT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQLXT.setFocusable(false);
        btnQLXT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLXT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQLXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLXTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQLXT);
        jToolBar1.add(jSeparator21);

        btnTTX.setBackground(new java.awt.Color(255, 204, 204));
        btnTTX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Info-24.png"))); // NOI18N
        btnTTX.setText("Thông tin xe");
        btnTTX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTTX.setFocusable(false);
        btnTTX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTTX.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTXActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTTX);
        jToolBar1.add(jSeparator15);

        btnHD.setBackground(new java.awt.Color(255, 204, 204));
        btnHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Contract-24.png"))); // NOI18N
        btnHD.setText("Phiếu Thuê");
        btnHD.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHD.setFocusable(false);
        btnHD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHD);
        jToolBar1.add(jSeparator16);

        btnPP.setBackground(new java.awt.Color(255, 204, 204));
        btnPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Note-24.png"))); // NOI18N
        btnPP.setText("Phiếu phạt");
        btnPP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPP.setFocusable(false);
        btnPP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPP);
        jToolBar1.add(jSeparator2);

        btnThongKe.setBackground(new java.awt.Color(255, 204, 204));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Reports-24.png"))); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThongKe.setFocusable(false);
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnThongKe);
        jToolBar1.add(jSeparator6);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Logout-24.png"))); // NOI18N
        jButton2.setText("Đăng Xuất");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tài khoản");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vai Trò");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jTextField1.setText("jTextField1");

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("Quản Lý Hồ Sơ    ");

        menuManageKhachHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManageKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Customer-24.png"))); // NOI18N
        menuManageKhachHang.setText("Khách Hàng");
        menuManageKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageKhachHangActionPerformed(evt);
            }
        });
        jMenu1.add(menuManageKhachHang);
        jMenu1.add(jSeparator1);

        menuManageNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManageNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Staff-24.png"))); // NOI18N
        menuManageNhanVien.setText("Nhân Viên");
        menuManageNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageNhanVienActionPerformed(evt);
            }
        });
        jMenu1.add(menuManageNhanVien);
        jMenu1.add(jsp2);

        menuManageLoaiXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Car-24.png"))); // NOI18N
        menuManageLoaiXe.setText("Loại Xe");

        menuManageXeMay.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManageXeMay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/motorcyclist-icon.png"))); // NOI18N
        menuManageXeMay.setText("Xe Máy");
        menuManageXeMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageXeMayActionPerformed(evt);
            }
        });
        menuManageLoaiXe.add(menuManageXeMay);
        menuManageLoaiXe.add(jSeparator18);

        menuManageXeTai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManageXeTai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Lorry-icon24.png"))); // NOI18N
        menuManageXeTai.setText("Xe Tải");
        menuManageXeTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageXeTaiActionPerformed(evt);
            }
        });
        menuManageLoaiXe.add(menuManageXeTai);
        menuManageLoaiXe.add(jSeparator19);

        menuManageOto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManageOto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Travel-BMV-icon24.png"))); // NOI18N
        menuManageOto.setText("Ô Tô");
        menuManageOto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageOtoActionPerformed(evt);
            }
        });
        menuManageLoaiXe.add(menuManageOto);

        jMenu1.add(menuManageLoaiXe);
        jMenu1.add(jSeparator3);

        menuManageThongTinXe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManageThongTinXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Info-24.png"))); // NOI18N
        menuManageThongTinXe.setText("Thông Tin Xe");
        menuManageThongTinXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageThongTinXeActionPerformed(evt);
            }
        });
        jMenu1.add(menuManageThongTinXe);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý Cho Thuê     ");

        menuManagerHopDong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManagerHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Contract-24.png"))); // NOI18N
        menuManagerHopDong.setText("Phiếu Thuê");
        menuManagerHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManagerHopDongActionPerformed(evt);
            }
        });
        jMenu2.add(menuManagerHopDong);
        jMenu2.add(jSeparator4);

        menuManagerPhieuPhat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManagerPhieuPhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Note-24.png"))); // NOI18N
        menuManagerPhieuPhat.setText("Phiếu Phạt");
        menuManagerPhieuPhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManagerPhieuPhatActionPerformed(evt);
            }
        });
        jMenu2.add(menuManagerPhieuPhat);
        jMenu2.add(jSeparator5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Báo cáo-Thống Kê     ");

        menuXuatBaoCao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuXuatBaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Reports-24.png"))); // NOI18N
        menuXuatBaoCao.setText("Thống Kê");
        menuXuatBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuXuatBaoCaoActionPerformed(evt);
            }
        });
        jMenu4.add(menuXuatBaoCao);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Hệ Thống");

        menuDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Logout-24.png"))); // NOI18N
        menuDangXuat.setText("Đăng Xuất");
        menuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangXuatActionPerformed(evt);
            }
        });
        jMenu5.add(menuDangXuat);
        jMenu5.add(jSeparator8);

        menuDoiMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Manager-24.png"))); // NOI18N
        menuDoiMatKhau.setText("Đổi Mật Khẩu");
        menuDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDoiMatKhauActionPerformed(evt);
            }
        });
        jMenu5.add(menuDoiMatKhau);
        jMenu5.add(jsp9);

        menuThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Cancel-24.png"))); // NOI18N
        menuThoat.setText("Thoát");
        menuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThoatActionPerformed(evt);
            }
        });
        jMenu5.add(menuThoat);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblMainBoard)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(tblMainBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuManagerPhieuPhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManagerPhieuPhatActionPerformed
         if (tblMainBoard.indexOfComponent(mPhieuPhat) == -1) {

            mPhieuPhat = new QuanLyPhieuPhat();
            ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/Note-24.png"));

            tblMainBoard.addTab("Quản Lý Phiếu Phạt", icon, mPhieuPhat, "Quản lý phiếu phạt");
        }

        tblMainBoard.setSelectedComponent(mPhieuPhat);
    }//GEN-LAST:event_menuManagerPhieuPhatActionPerformed

    private void menuManageKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageKhachHangActionPerformed
        // TODO add your handling code here:
       if (tblMainBoard.indexOfComponent(mQuanLyKhachHang) == -1) {

            mQuanLyKhachHang = new QuanLyKhachHang();
            ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/Customer-24.png"));

            tblMainBoard.addTab("Quản Lý Khách Hàng", icon, mQuanLyKhachHang, "Quản lý khách hàng");
        }

        tblMainBoard.setSelectedComponent(mQuanLyKhachHang);
        
        
        
    }//GEN-LAST:event_menuManageKhachHangActionPerformed

    private void menuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangXuatActionPerformed
        // TODO add your handling code here:
        
        int n = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn đăng xuất", "Thông báo", 
                JOptionPane.OK_CANCEL_OPTION);
        
        if(n == JOptionPane.OK_OPTION){
        LoginDialog loginDialog = new LoginDialog(this, true);
        loginDialog.setVisible(true);
        MainForm.tblMainBoard.removeAll();
       
        }
        
        processloginSuccessful();
    }//GEN-LAST:event_menuDangXuatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LoginDialog dialog = new LoginDialog(this, true);
        dialog.setVisible(true);
        
        processloginSuccessful();
    }//GEN-LAST:event_formWindowOpened

    private void menuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuThoatActionPerformed

    private void menuManageNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageNhanVienActionPerformed
        // TODO add your handling code here:
        if (tblMainBoard.indexOfComponent(mQuanLyNhanVien) == -1) {

            mQuanLyNhanVien = new QuanLyNhanVien();
            ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/Staff-24.png"));
            
            tblMainBoard.addTab("Quản Lý Nhân Viên ", icon , mQuanLyNhanVien, "Quản lý thông nhân viên");
        }

        tblMainBoard.setSelectedComponent(mQuanLyNhanVien);
    }//GEN-LAST:event_menuManageNhanVienActionPerformed

    private void menuManageThongTinXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageThongTinXeActionPerformed
        // TODO add your handling code here:
         if (tblMainBoard.indexOfComponent(mQuanLyThongTinXe) == -1) {

            mQuanLyThongTinXe = new QuanLyThongTinXe();
            ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/Info-24.png"));
            
            tblMainBoard.addTab("Quản Lý Thông Tin Xe ", icon , mQuanLyThongTinXe, "Quản lý thông tin xe");
        }

        tblMainBoard.setSelectedComponent(mQuanLyThongTinXe);
    }//GEN-LAST:event_menuManageThongTinXeActionPerformed

    private void menuDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDoiMatKhauActionPerformed
        // TODO add your handling code here:
        if (tblMainBoard.indexOfComponent(mDoiMaKhau) == -1) {

            mDoiMaKhau = new DoiMaKhau();
            ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/Manager-24.png"));
            
            tblMainBoard.addTab("Đổi Mật Khẩu ", icon , mDoiMaKhau, "Đổi mật khẩu");
        }

        tblMainBoard.setSelectedComponent(mDoiMaKhau);
       
        
       
       
    }//GEN-LAST:event_menuDoiMatKhauActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        menuDoiMatKhauActionPerformed(evt);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKHActionPerformed
       menuManageKhachHangActionPerformed(evt);
    }//GEN-LAST:event_btnQLKHActionPerformed

    private void btnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNVActionPerformed
        menuManageNhanVienActionPerformed(evt);
    }//GEN-LAST:event_btnQLNVActionPerformed

    private void btnQLXMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLXMActionPerformed
        menuManageXeMayActionPerformed(evt);
    }//GEN-LAST:event_btnQLXMActionPerformed

    private void btnTTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTXActionPerformed
        menuManageThongTinXeActionPerformed(evt);
    }//GEN-LAST:event_btnTTXActionPerformed

    private void menuManagerHopDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManagerHopDongActionPerformed
        if (tblMainBoard.indexOfComponent(mQuanLyPhieuThue) == -1) {

            mQuanLyPhieuThue = new QuanLyPhieuThue();
            ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/Contract-24.png"));

            tblMainBoard.addTab("Quản lý phiếu thuê", icon, mQuanLyPhieuThue, "Quản lý phiếu thuê");
        }

        tblMainBoard.setSelectedComponent(mQuanLyPhieuThue);
    }//GEN-LAST:event_menuManagerHopDongActionPerformed

    private void btnHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDActionPerformed
        menuManagerHopDongActionPerformed(evt);
    }//GEN-LAST:event_btnHDActionPerformed

    private void btnPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPPActionPerformed
        menuManagerPhieuPhatActionPerformed(evt);
    }//GEN-LAST:event_btnPPActionPerformed

    private void menuManageXeMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageXeMayActionPerformed
        // TODO add your handling code here:
        if (tblMainBoard.indexOfComponent(mQuanLyXeMay) == -1) {

            mQuanLyXeMay = new QuanLyXeMay();
            ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/motorcyclist-icon.png"));

            tblMainBoard.addTab("Quản lý xe máy", icon, mQuanLyXeMay, "Quản lý xe máy");
        }

        tblMainBoard.setSelectedComponent(mQuanLyXeMay);
    }//GEN-LAST:event_menuManageXeMayActionPerformed

    private void menuManageXeTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageXeTaiActionPerformed
        // TODO add your handling code here:
        if (tblMainBoard.indexOfComponent(mQuanLyXeTai) == -1) {

            mQuanLyXeTai = new QuanLyXeTai();
            ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/Lorry-icon24.png"));

            tblMainBoard.addTab("Quản lý xe tải", icon, mQuanLyXeTai, "Quản lý xe tải");
        }

        tblMainBoard.setSelectedComponent(mQuanLyXeTai);
    }//GEN-LAST:event_menuManageXeTaiActionPerformed

    private void menuManageOtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageOtoActionPerformed
        // TODO add your handling code here:
        if (tblMainBoard.indexOfComponent(mQuanLyOTo) == -1) {

            mQuanLyOTo = new QuanLyOTo();
            ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/Travel-BMV-icon24.png"));

            tblMainBoard.addTab("Quản lý ô tô", icon, mQuanLyOTo, "Quản lý ô tô");
        }

        tblMainBoard.setSelectedComponent(mQuanLyOTo);
    }//GEN-LAST:event_menuManageOtoActionPerformed

    private void btnQLOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLOTActionPerformed
        menuManageOtoActionPerformed(evt);
    }//GEN-LAST:event_btnQLOTActionPerformed

    private void btnQLXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLXTActionPerformed
        menuManageXeTaiActionPerformed(evt);
    }//GEN-LAST:event_btnQLXTActionPerformed

    private void menuXuatBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuXuatBaoCaoActionPerformed
        // TODO add your handling code here:
        if (tblMainBoard.indexOfComponent(mThongKeView) == -1) {

            mThongKeView = new ThongKeView();
            ImageIcon icon = new ImageIcon(getClass().getResource("/ICON/Reports-24.png"));

            tblMainBoard.addTab("Thống Kê", icon, mThongKeView, "Thống kê");
        }

        tblMainBoard.setSelectedComponent(mThongKeView);
    }//GEN-LAST:event_menuXuatBaoCaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menuDangXuatActionPerformed(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        menuXuatBaoCaoActionPerformed(evt);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void tblMainBoardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainBoardMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMainBoardMouseExited
    
    private void processloginSuccessful(){
        jLabel1.setText(ShareData.takhoanDangNhap.getTenND());
        jLabel2.setText(ShareData.takhoanDangNhap.getChucVu());
        
        if(ShareData.takhoanDangNhap.getChucVu().trim().equals("Quản Lý")){
            menuDoiMatKhau.setVisible(true);
            menuManageNhanVien.setVisible(true);
            btnDoiMatKhau.setVisible(true); 
            btnQLNV.setVisible(true);
            jsp2.setVisible(true);
            jsp9.setVisible(true);
            jsp10.setVisible(true);
        }else{
            menuDoiMatKhau.setVisible(false);
            menuManageNhanVien.setVisible(false);
            btnQLNV.setVisible(false);
            jsp2.setVisible(false);
            jsp9.setVisible(false);
            jsp10.setVisible(false);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnHD;
    private javax.swing.JButton btnPP;
    private javax.swing.JButton btnQLKH;
    private javax.swing.JButton btnQLNV;
    private javax.swing.JButton btnQLOT;
    private javax.swing.JButton btnQLXM;
    private javax.swing.JButton btnQLXT;
    private javax.swing.JButton btnTTX;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator20;
    private javax.swing.JToolBar.Separator jSeparator21;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar.Separator jsp10;
    private javax.swing.JPopupMenu.Separator jsp2;
    private javax.swing.JPopupMenu.Separator jsp9;
    private javax.swing.JMenuItem menuDangXuat;
    private javax.swing.JMenuItem menuDoiMatKhau;
    private javax.swing.JMenuItem menuManageKhachHang;
    private javax.swing.JMenu menuManageLoaiXe;
    private javax.swing.JMenuItem menuManageNhanVien;
    private javax.swing.JMenuItem menuManageOto;
    private javax.swing.JMenuItem menuManageThongTinXe;
    private javax.swing.JMenuItem menuManageXeMay;
    private javax.swing.JMenuItem menuManageXeTai;
    private javax.swing.JMenuItem menuManagerHopDong;
    private javax.swing.JMenuItem menuManagerPhieuPhat;
    private javax.swing.JMenuItem menuThoat;
    private javax.swing.JMenuItem menuXuatBaoCao;
    public static javax.swing.JTabbedPane tblMainBoard;
    // End of variables declaration//GEN-END:variables
}
