/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DATA.DataValidator;
import DAO.OToDao;
import DAO.ThongTinXeDao;
import DATA.MessageDialogHelper;
import DTO.OTo;
import DTO.ThongTinXe;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLyOTo extends javax.swing.JPanel {

    private MainForm parentForm;
    private DefaultTableModel tblModel;

    /**
     * Creates new form QuanLyLoaiXe
     */
    public QuanLyOTo() {
        initComponents();

        initTable();

        loadDataToTable();

    }

    public void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã ô tô", "Tên Xe", "Hãng Sản Xuất", "Năm Sản Xuất", "Giá Bán", "Màu Sơn", "Kiểu Động Cơ", "Số Chỗ Ngồi"});
        tblLoaiXe.setModel(tblModel);
    }

    private void loadDataToTable() {
        try {
            OToDao dao = new OToDao();
            List<OTo> list = dao.findAll();
            tblModel.setRowCount(0);
            for (OTo oto : list) {
                tblModel.addRow(new Object[]{
                    oto.getMaOT(), oto.getTenXe(), oto.getHangSanXuat(), oto.getNamSanXuat(), oto.getGiaBan(), oto.getMauSon(), oto.getKieuDongCo(), oto.getSoChoNgoi()
                });
            }

            tblModel.fireTableDataChanged();

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }

    private void loadDataToTableByColor() {
        try {
            OToDao dao = new OToDao();
            List<OTo> list = dao.findAll();
            tblModel.setRowCount(0);
            for (OTo oto : list) {
                tblModel.addRow(new Object[]{
                    oto.getMaOT(), oto.getTenXe(), oto.getHangSanXuat(), oto.getNamSanXuat(), oto.getGiaBan(), oto.getMauSon(), oto.getKieuDongCo(), oto.getSoChoNgoi()
                });
            }

            tblModel.fireTableDataChanged();

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        txtKieuDongCo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiXe = new javax.swing.JTable();
        txtHangSanXuat = new javax.swing.JTextField();
        txtNamSanXuat = new javax.swing.JTextField();
        txtMau = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMaLoaiXe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTenLoaiXe = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtMauSacTK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        txtSoChoNgoi = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1361, 561));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Quản Lý Ô Tô");

        jLabel3.setText("Hãng Sản Xuất:");

        jLabel4.setText("Năm Sản Xuất:");

        jLabel5.setText("Giá bán:");

        jLabel6.setText("Kiểu Đông Cơ:");

        jLabel7.setText("Số Chỗ Ngồi:");

        jLabel10.setText("Màu:");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Add-24.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Edit-24.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Delete-24.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/reset.png"))); // NOI18N
        btnXoaTrang.setText("Reset");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        tblLoaiXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLoaiXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiXeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiXe);

        jLabel11.setText("Mã Loại Xe:");

        jLabel12.setText("Tên Loại Xe:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        jLabel2.setText("Nhập màu sắc muốn tìm:");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Search-24.png"))); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtMauSacTK, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnTimKiem)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMauSacTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnTimKiem)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Cancel-24.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnThem)
                                    .addGap(28, 28, 28)
                                    .addComponent(btnSua)
                                    .addGap(34, 34, 34)
                                    .addComponent(btnXoa)
                                    .addGap(31, 31, 31)
                                    .addComponent(btnXoaTrang)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnDong))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel5))
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSoChoNgoi)
                                        .addComponent(txtKieuDongCo, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                        .addComponent(txtGiaBan)
                                        .addComponent(txtMau)))))))
                .addGap(0, 774, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel4))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTenLoaiXe, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(txtHangSanXuat)
                                        .addComponent(txtMaLoaiXe))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKieuDongCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(txtMaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTenLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtSoChoNgoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtNamSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnSua)
                        .addComponent(btnXoa)
                        .addComponent(btnXoaTrang)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validdateEmpty(txtMaLoaiXe, sb, "Mã loại xe không được bỏ trống");
        DataValidator.validdateEmpty(txtTenLoaiXe, sb, "Tên loại xe không được bỏ trống");
        DataValidator.validdateEmpty(txtNamSanXuat, sb, "Năm sản xuất không được bỏ trống");
        DataValidator.validdateEmpty(txtGiaBan, sb, "Giá bán không được bỏ trống");
        DataValidator.validdateEmpty(txtMau, sb, "Màu xe không được bỏ trống");
        DataValidator.validdateEmpty(txtHangSanXuat, sb, "Hãng sản xuất không được bỏ trống");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try {
            OTo lx = new OTo();
            lx.setMaOT(txtMaLoaiXe.getText().trim());
            lx.setTenXe(txtTenLoaiXe.getText());
            lx.setHangSanXuat(txtHangSanXuat.getText());
            lx.setNamSanXuat(txtNamSanXuat.getText());
            lx.setGiaBan(txtGiaBan.getText());
            lx.setMauSon(txtMau.getText());
            lx.setKieuDongCo(txtKieuDongCo.getText());
            lx.setSoChoNgoi(Integer.parseInt(txtSoChoNgoi.getText()));
            OToDao dao = new OToDao();
            boolean CheckOTo = false;
            List<OTo> lot = dao.findAll();
            for (OTo oto : lot) {
                if (oto.getMaOT().trim().equalsIgnoreCase(txtMaLoaiXe.getText().trim())) {
                    CheckOTo = true;
                };
            }
            if (CheckOTo == true) {
                MessageDialogHelper.showMessageDialog(parentForm, "Xe đã tồn tại!", "Cảnh báo!");
                return;
            } else {
                if (dao.insert(lx)) {
                    MessageDialogHelper.showMessageDialog(parentForm, "Xe đã được lưu", "Thông báo");
                    btnXoaTrangActionPerformed(evt);
                    loadDataToTable();
                } else {
                    MessageDialogHelper.showConfirmDialog(parentForm, "Xe không được lưu do lỗi", "Cảnh báo");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validdateEmpty(txtMaLoaiXe, sb, "Mã loại xe không được bỏ trống");
        DataValidator.validdateEmpty(txtTenLoaiXe, sb, "Tên loại xe không được bỏ trống");
        DataValidator.validdateEmpty(txtNamSanXuat, sb, "Năm sản xuất không được bỏ trống");
        DataValidator.validdateEmpty(txtGiaBan, sb, "Giá bán không được bỏ trống");
        DataValidator.validdateEmpty(txtMau, sb, "Màu xe không được bỏ trống");
        DataValidator.validdateEmpty(txtHangSanXuat, sb, "Hãng sản xuất không được bỏ trống");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }

        if (MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn cập nhật  xe không?", "Hỏi") == JOptionPane.NO_OPTION) {
            return;
        }

        try {
            OTo lx = new OTo();

            lx.setTenXe(txtTenLoaiXe.getText());
            lx.setHangSanXuat(txtHangSanXuat.getText());
            lx.setNamSanXuat(txtNamSanXuat.getText());
            lx.setGiaBan(txtGiaBan.getText());
            lx.setMauSon(txtMau.getText());
            lx.setKieuDongCo(txtKieuDongCo.getText());
            lx.setSoChoNgoi(Integer.parseInt(txtSoChoNgoi.getText()));

            lx.setMaOT(txtMaLoaiXe.getText());

            OToDao dao = new OToDao();
            if (dao.update(lx)) {
                MessageDialogHelper.showMessageDialog(parentForm, "Xe đã được cập nhật", "Thông báo");
                btnXoaTrangActionPerformed(evt);
                loadDataToTable();
            } else {
                MessageDialogHelper.showConfirmDialog(parentForm, "Xe không được cập nhật do lỗi", "Cảnh báo");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validdateEmpty(txtMaLoaiXe, sb, "Mã loại xe không được bỏ trống");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }

        if (MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn xóa xe không?", "Hỏi") == JOptionPane.NO_OPTION) {
            return;
        }

        try {

            boolean checkMLX = false;
            
            
            ThongTinXeDao ttxd = new ThongTinXeDao();
            List<ThongTinXe> lttx = ttxd.findAll();
            for(ThongTinXe ttx : lttx){
                if(ttx.getMaOT() != null){
                    if(ttx.getMaOT().trim().equalsIgnoreCase(txtMaLoaiXe.getText().trim())){
                        checkMLX = true;
                        break;
                    }
                }
                

            }
            OToDao dao = new OToDao();
            if(checkMLX == true){
                MessageDialogHelper.showMessageDialog(parentForm, "Vui lòng xóa mã loại xe này trong bảng thông tin xe!", "Cảnh báo");
                return;
            }else{
                if (dao.delete(txtMaLoaiXe.getText())) {
                    MessageDialogHelper.showMessageDialog(parentForm, "Xe đã được xóa", "Thông báo");
                    btnXoaTrangActionPerformed(evt);
                    loadDataToTable();
                } else {
                    MessageDialogHelper.showConfirmDialog(parentForm, "Xe không được xóa do lỗi", "Cảnh báo");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        // TODO add your handling code here:
        txtMaLoaiXe.setText("");
        txtTenLoaiXe.setText("");
        txtHangSanXuat.setText("");
        txtNamSanXuat.setText("");
        txtGiaBan.setText("");
        txtMau.setText("");
        txtKieuDongCo.setText("");
        txtSoChoNgoi.setText("");
        loadDataToTable();

    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void tblLoaiXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiXeMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblLoaiXe.getSelectedRow();

            if (row >= 0) {
                String id = (String) tblLoaiXe.getValueAt(row, 0);
                OToDao dao = new OToDao();
                OTo lx = dao.findById(id);

                if (lx != null) {
                    txtMaLoaiXe.setText(lx.getMaOT());

                    txtTenLoaiXe.setText(lx.getTenXe());
                    txtHangSanXuat.setText(lx.getHangSanXuat());
                    txtNamSanXuat.setText(lx.getNamSanXuat());
                    txtGiaBan.setText(lx.getGiaBan());
                    txtMau.setText(lx.getMauSon());
                    txtKieuDongCo.setText(lx.getKieuDongCo());
                    txtSoChoNgoi.setText("" + lx.getSoChoNgoi());

                }

            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblLoaiXeMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
            OToDao dao = new OToDao();
            List<OTo> list = dao.findByColor(txtMauSacTK.getText().trim());
            if (list.size() > 0) {
                tblModel.setRowCount(0);
                for (OTo oto : list) {
                    tblModel.addRow(new Object[]{
                        oto.getMaOT(), oto.getTenXe(), oto.getHangSanXuat(), oto.getNamSanXuat(), oto.getGiaBan(), oto.getMauSon(), oto.getKieuDongCo(), oto.getSoChoNgoi()
                    });
                    tblModel.fireTableDataChanged();
                }

            } else {
                MessageDialogHelper.showMessageDialog(parentForm, "Không tim thấy ô tô cần tìm!", "Thông báo !");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        int index = MainForm.tblMainBoard.indexOfComponent(this);
        MainForm.tblMainBoard.removeTabAt(index);
    }//GEN-LAST:event_btnDongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblLoaiXe;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtHangSanXuat;
    private javax.swing.JTextField txtKieuDongCo;
    private javax.swing.JTextField txtMaLoaiXe;
    private javax.swing.JTextField txtMau;
    private javax.swing.JTextField txtMauSacTK;
    private javax.swing.JTextField txtNamSanXuat;
    private javax.swing.JTextField txtSoChoNgoi;
    private javax.swing.JTextField txtTenLoaiXe;
    // End of variables declaration//GEN-END:variables
}
