/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ThongTinXeDao;
import DATA.DataValidator;
import DAO.XeTaiDao;
import DATA.MessageDialogHelper;
import DTO.ThongTinXe;
import DTO.XeTai;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLyXeTai extends javax.swing.JPanel {

    private MainForm parentForm;
    private DefaultTableModel tblModel;

    /**
     * Creates new form QuanLyLoaiXe
     */
    public QuanLyXeTai() {
        initComponents();
        
        
        initTable();
        
        loadDataToTable();

    }

   

    public void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã Loại Xe", "Tên Loại Xe", "Hãng Sản Xuất", "Năm Sản Xuất", "Giá Bán", "Màu Sơn", "Trọng Tải(Tấn)"});
        tblXeTai.setModel(tblModel);
    }

    private void loadDataToTable() {
        try {
            XeTaiDao dao = new XeTaiDao();
            List<XeTai> list = dao.findAll();
            tblModel.setRowCount(0);
            for (XeTai xetai : list) {
                tblModel.addRow(new Object[]{
                    xetai.getMaXT(), xetai.getTenXe(), xetai.getHangSanXuat(), xetai.getNamSanXuat(), xetai.getGiaBan(),  xetai.getMauSon(),  xetai.getTrongTai()
                });
            }

            tblModel.fireTableDataChanged();

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        txtTrongTai = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblXeTai = new javax.swing.JTable();
        txtHangSanXuat = new javax.swing.JTextField();
        txtNamSanXuat = new javax.swing.JTextField();
        txtMau = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMaLoaiXe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTenLoaiXe = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtMauSacTK = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Quản Lý Xe Tải");

        jLabel3.setText("Hãng Sản Xuất:");

        jLabel4.setText("Năm Sản Xuất:");

        jLabel5.setText("Giá bán:");

        jLabel8.setText("Trọng Tải:");

        jLabel10.setText("Màu:");

        txtTrongTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTrongTaiActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Add-24.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Edit-24.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Delete-24.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/reset.png"))); // NOI18N
        btnXoaTrang.setText("Reset");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        tblXeTai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblXeTai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblXeTaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblXeTai);

        jLabel11.setText("Mã Loại Xe:");

        jLabel12.setText("Tên Loại Xe:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        jLabel2.setText("Nhập màu sắc muốn tìm:");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Search-24.png"))); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtMauSacTK, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnTimKiem)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTimKiem)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMauSacTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Cancel-24.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaLoaiXe)
                                    .addComponent(txtTenLoaiXe)
                                    .addComponent(txtNamSanXuat)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTrongTai, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHangSanXuat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMau, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnThem)
                                .addGap(33, 33, 33)
                                .addComponent(btnSua)
                                .addGap(29, 29, 29)
                                .addComponent(btnXoa)
                                .addGap(31, 31, 31)
                                .addComponent(btnXoaTrang)
                                .addGap(21, 21, 21)
                                .addComponent(btnDong))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHangSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTrongTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnXoaTrang)
                    .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validdateEmpty(txtMaLoaiXe, sb, "Mã loại xe không được bỏ trống");
        DataValidator.validdateEmpty(txtTenLoaiXe, sb, "Tên loại xe không được bỏ trống");
        DataValidator.validdateEmpty(txtNamSanXuat, sb, "Năm sản xuất không được bỏ trống");
        DataValidator.validdateEmpty(txtGiaBan, sb, "Giá bán không được bỏ trống");
        DataValidator.validdateEmpty(txtMau, sb, "Màu xe không được bỏ trống");
        DataValidator.validdateEmpty(txtHangSanXuat, sb, "Hãng sản xuất không được bỏ trống");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try {
            XeTai lx = new XeTai();
            lx.setMaXT(txtMaLoaiXe.getText().trim());
            lx.setTenXe(txtTenLoaiXe.getText());
            lx.setHangSanXuat(txtHangSanXuat.getText());
            lx.setNamSanXuat(txtNamSanXuat.getText());
            lx.setGiaBan(txtGiaBan.getText());
            lx.setMauSon(txtMau.getText());
            
            lx.setTrongTai(Float.parseFloat(txtTrongTai.getText()));
            XeTaiDao dao = new XeTaiDao();
            boolean CheckXT = false;
            List<XeTai> lxt = dao.findAll();
            for(XeTai xetai : lxt){
                if(xetai.getMaXT().trim().equalsIgnoreCase(txtMaLoaiXe.getText().trim())){
                    CheckXT = true;
                };
            }
            if(CheckXT == true){
                MessageDialogHelper.showMessageDialog(parentForm, "Xe đã tồn tại!","Cảnh báo!");
                return;
            }else{
                if (dao.insert(lx)) {
                    MessageDialogHelper.showMessageDialog(parentForm, "Xe đã được lưu", "Thông báo");
                    btnXoaTrangActionPerformed(evt);
                    loadDataToTable();
                } else {
                    MessageDialogHelper.showConfirmDialog(parentForm, "Xe không được lưu do lỗi", "Cảnh báo");
                }
            }
            

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validdateEmpty(txtMaLoaiXe, sb, "Mã loại xe không được bỏ trống");
        DataValidator.validdateEmpty(txtTenLoaiXe, sb, "Tên loại xe không được bỏ trống");
        DataValidator.validdateEmpty(txtNamSanXuat, sb, "Năm sản xuất không được bỏ trống");
        DataValidator.validdateEmpty(txtGiaBan, sb, "Giá bán không được bỏ trống");
        DataValidator.validdateEmpty(txtMau, sb, "Màu xe không được bỏ trống");
        DataValidator.validdateEmpty(txtHangSanXuat, sb, "Hãng sản xuất không được bỏ trống");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }

        if (MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn cập nhật  xe không?", "Hỏi") == JOptionPane.NO_OPTION) {
            return;
        }

        try {
            XeTai lx = new XeTai();    
            lx.setTenXe(txtTenLoaiXe.getText());
            lx.setHangSanXuat(txtHangSanXuat.getText());
            lx.setNamSanXuat(txtNamSanXuat.getText());
            lx.setGiaBan(txtGiaBan.getText());
            lx.setMauSon(txtMau.getText());
            lx.setTrongTai(Float.parseFloat(txtTrongTai.getText()));
            lx.setMaXT(txtMaLoaiXe.getText());
            

            XeTaiDao dao = new XeTaiDao();
            if (dao.update(lx)) {
                MessageDialogHelper.showMessageDialog(parentForm, "Xe đã được cập nhật", "Thông báo");
                 btnXoaTrangActionPerformed(evt);
                loadDataToTable();
            } else {
                MessageDialogHelper.showConfirmDialog(parentForm, "Xe không được cập nhật do lỗi", "Cảnh báo");
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validdateEmpty(txtMaLoaiXe, sb, "Mã loại xe không được bỏ trống");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }

        if (MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn xóa loại xe không?", "Hỏi") == JOptionPane.NO_OPTION) {
            return;
        }

        try {

           boolean checkMLX = false;
            ThongTinXeDao ttxd = new ThongTinXeDao();
            List<ThongTinXe> lttx = ttxd.findAll();
            for(ThongTinXe ttx : lttx){
                if(ttx.getMaXT() != null){
                    if(ttx.getMaXT().trim().equalsIgnoreCase(txtMaLoaiXe.getText().trim())){
                        checkMLX = true;
                        break;
                    }
                }
            }
            XeTaiDao dao = new XeTaiDao();
            if(checkMLX == true){
                MessageDialogHelper.showMessageDialog(parentForm, "Vui lòng xóa mã loại xe này bên bảng thông tin xe trước! ", "Cảnh báo");
                return;
            }else{
                if (dao.delete(txtMaLoaiXe.getText())) {
                    MessageDialogHelper.showMessageDialog(parentForm, "Xe đã được xóa", "Thông báo");
                    btnXoaTrangActionPerformed(evt);
                    loadDataToTable();
                } else {
                    MessageDialogHelper.showConfirmDialog(parentForm, "Xe không được xóa do lỗi", "Cảnh báo");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        // TODO add your handling code here:
        txtMaLoaiXe.setText("");
        txtTenLoaiXe.setText("");
        txtHangSanXuat.setText("");
        txtNamSanXuat.setText("");
        txtGiaBan.setText("");
        txtMau.setText("");
        txtTrongTai.setText("");
        loadDataToTable();
       

    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void tblXeTaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblXeTaiMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblXeTai.getSelectedRow();

            if (row >= 0) {
                String id = (String) tblXeTai.getValueAt(row, 0);
                XeTaiDao dao = new XeTaiDao();
                XeTai lx = dao.findById(id);

                if (lx != null) {
                    txtMaLoaiXe.setText(lx.getMaXT());
                    txtTenLoaiXe.setText(lx.getTenXe());
                    txtHangSanXuat.setText(lx.getHangSanXuat());
                    txtNamSanXuat.setText(lx.getNamSanXuat());
                    txtGiaBan.setText(lx.getGiaBan());
                    txtMau.setText(lx.getMauSon());
                    txtTrongTai.setText(""+lx.getTrongTai());
               
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblXeTaiMouseClicked

    private void txtTrongTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrongTaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrongTaiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        try {
                XeTaiDao dao = new XeTaiDao();
                List<XeTai> list = dao.findByColor(txtMauSacTK.getText().trim());
                if(list.size() > 0){
                    tblModel.setRowCount(0);
                   for (XeTai xetai : list) {
                        tblModel.addRow(new Object[]{
                            xetai.getMaXT(), xetai.getTenXe(), xetai.getHangSanXuat(), xetai.getNamSanXuat(), xetai.getGiaBan(),  xetai.getMauSon(),  xetai.getTrongTai()
                        });
                    }
                    tblModel.fireTableDataChanged();
                }else {
                     MessageDialogHelper.showMessageDialog(parentForm,  "Không tim thấy ô tô cần tìm!", "Thông báo !");
                     
                }
                

            } catch (Exception e) {
                e.printStackTrace();
                MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
            }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        int index= MainForm.tblMainBoard.indexOfComponent(this);
        MainForm.tblMainBoard.removeTabAt(index);
    }//GEN-LAST:event_btnDongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblXeTai;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtHangSanXuat;
    private javax.swing.JTextField txtMaLoaiXe;
    private javax.swing.JTextField txtMau;
    private javax.swing.JTextField txtMauSacTK;
    private javax.swing.JTextField txtNamSanXuat;
    private javax.swing.JTextField txtTenLoaiXe;
    private javax.swing.JTextField txtTrongTai;
    // End of variables declaration//GEN-END:variables
}
